---
- name: AuthGateway | Render email whitelist
  template:
    dest: '{{ authgateway_install_path }}/allowed.emails'
    group: '{{ authgateway_group }}'
    owner: '{{ authgateway_user }}'
    mode: 0640
    src: 'allowed.emails'
  when: authgateway_extra_emails|length
  notify:
    - Restart AuthGateway

- name: AuthGateway | Render configuration
  template:
    dest: '{{ authgateway_install_path }}/auth-gateway.yaml'
    group: '{{ authgateway_group }}'
    owner: '{{ authgateway_user }}'
    mode: 0640
    src: 'auth-gateway.yaml'
  notify:
    - Restart AuthGateway

- name: AuthGateway | Render acmetool target file
  template:
    dest: '{{ authgateway_acmetool_target }}'
    mode: 0644
    src: 'acmetool.yml'
  when: authgateway_acmetool_target is string
