---
- name: AuthGateway | Configure auth proxy
  include_tasks: 'oauth2_proxy.yml'
  when: authgateway_configure_oauth2_proxy

- name: AuthGateway | Install
  import_tasks: 'tasks/install.yml'

- name: AuthGateway | Configure
  import_tasks: 'tasks/configure.yml'

- name: AuthGateway | Configure service
  import_tasks: 'tasks/service.yml'
