---
- name: AuthGateway | Install systemd service
  template:
    dest: '/usr/lib/systemd/system/authgateway.service'
    mode: 0644
    src: 'authgateway.service'
  when: ansible_service_mgr == 'systemd'

- name: AuthGateway | Configure service
  service:
    enabled: true
    name: authgateway
    state: started
  when: ansible_service_mgr == 'systemd'

- name: AuthGateway | Render acmetool service reload hook
  template:
    dest: '{{ authgateway_acmetool_hook }}'
    mode: 0755
    src: 'acmetool.hook'
  when:
    - ansible_service_mgr == 'systemd'
    - authgateway_acmetool_hook is string
