---
- name: AuthGateway | Install systemd service
  template:
    dest: '/usr/lib/systemd/system/authgateway.service'
    mode: 0644
    src: 'tasks/template/authgateway.service'
  when: ansible_service_mgr == 'systemd'

- name: AuthGateway | Configure service
  service:
    enabled: true
    name: authgateway
    state: started
  when: ansible_service_mgr == 'systemd'
